# Generated by Django 4.1.2 on 2022-10-11 08:42

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"verbose_name_plural": "Service Categories",},
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=255)),
                (
                    "image_1",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="images/service/", verbose_name="Image"
                    ),
                ),
                (
                    "image_2",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="images/service/", verbose_name="Image"
                    ),
                ),
                (
                    "image_3",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="images/service/", verbose_name="Image"
                    ),
                ),
                ("details", models.CharField(max_length=1200)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.servicecategory",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Product",},
        ),
    ]
